language: objective-c

os:
    - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode12.4
env:
  - BUILD="pushd Examples && pod repo update && pod install && set -o pipefail && (xcodebuild -workspace Examples.xcworkspace -scheme Example -destination 'platform=iOS Simulator,name=iPhone 12' build) | xcpretty"
  - BUILD="pod repo update && pod lib lint RxFeedback.podspec --verbose"
  - BUILD="swift build"
  - BUILD="carthage update --platform ios --use-xcframeworks && carthage build --no-skip-current --platform iOS --use-xcframeworks && set -o pipefail && (xcodebuild -project RxFeedback.xcodeproj -scheme RxFeedback -destination 'platform=iOS Simulator,name=iPhone 12' test) | xcpretty"
  - BUILD="carthage update --platform tvOS --use-xcframeworks && carthage build --no-skip-current --platform tvOS --use-xcframeworks"

script: eval "${BUILD}"

notifications:
  slack: rxswift:3ykt2Z61f8GkdvhCZTYPduOL
  email: false

after_success:
  - sleep 5 # workaround https://github.com/travis-ci/travis-ci/issues/4725

