version: 2.0

jobs:
  carthage:
    macos:
      xcode: "9.2.0"

    working_directory: ~/carthage
    steps:
      - checkout
      - restore_cache:
          key: carthage-cache
      - run:
          name: Install Homebrew Dependencies
          command: brew upgrade carthage
      - run:
          name: Carthage Build tvOS
          command: carthage update --platform tvOS && carthage build --no-skip-current --platform tvOS
      - run:
          name: Carthage Build iOS
          command: carthage update --platform ios && carthage build --no-skip-current --platform iOS
      - run:
          name: Test
          command: xcodebuild -project RxFeedback.xcodeproj -scheme RxFeedbackTests -destination 'platform=iOS Simulator,name=iPhone 7' test | xcpretty
      - run:
          name: Build
          command: xcodebuild -project RxFeedback.xcodeproj -scheme Example -destination 'platform=iOS Simulator,name=iPhone 7' build | xcpretty
      - save_cache:
          key: carthage-cache
          paths:
            - Carthage

workflows:
  version: 2
  build:
    jobs:
      - carthage
      